# temp.py
"""
Generates anytime behavior comparison plots (Fixed vs Adaptive scheduling).

Reads log CSV files from GA runs and produces:
  - A combined .dat file for gnuplot
  - A gnuplot script (.gp)
  - EPS and PNG output plots
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Optional
import shutil
import subprocess

import pandas as pd


# ============================================================
# Configuration
# ============================================================

@dataclass(frozen=True)
class PlotConfig:
    """Visual and path settings for the anytime plot."""
    # Input files
    log_fixed_csv: str = "log_fixed.csv"
    log_adaptive_csv: str = "log_adaptive.csv"

    # Output files
    out_dat: str = "data_anytime_4curves.dat"
    out_gp: str = "plot_anytime_4curves.gp"
    out_eps: str = "anytime_4curves.eps"

    # Visual settings
    png_font_size: int = 32
    png_key_font_size: int = 24
    line_width: int = 4

    # Column names
    gen_col: str = "gen"
    best_col: str = "best_fitness"
    avg_col: str = "avg_fitness"

    @property
    def out_png(self) -> str:
        return self.out_eps.replace(".eps", ".png")


# Curve labels for the legend
CURVE_LABELS = {
    "fixed_best": "fixed: best fitness",
    "fixed_avg": "fixed: avg fitness",
    "adapt_best": "adaptive: best fitness",
    "adapt_avg": "adaptive: avg fitness",
}


# ============================================================
# Data Loading Utilities
# ============================================================

def read_csv_safe(path: str) -> pd.DataFrame:
    """Read CSV file with error handling."""
    try:
        return pd.read_csv(path)
    except FileNotFoundError:
        raise SystemExit(f"Error: '{path}' not found in current directory.")


def ensure_numeric_columns(df: pd.DataFrame, cols: list[str]) -> pd.DataFrame:
    """Ensure specified columns exist and are numeric."""
    for col in cols:
        if col not in df.columns:
            raise SystemExit(f"Error: missing required column '{col}' in CSV")
        df[col] = pd.to_numeric(df[col], errors="coerce")
    return df


def load_and_prepare_log(
    path: str,
    gen_col: str,
    value_cols: list[str],
    prefix: str,
) -> pd.DataFrame:
    """Load a log CSV and rename value columns with a prefix."""
    df = read_csv_safe(path)
    df = ensure_numeric_columns(df, [gen_col] + value_cols)
    df = df[[gen_col] + value_cols].copy()
    df = df.sort_values(gen_col)

    # Rename columns: best_fitness -> {prefix}_best, avg_fitness -> {prefix}_avg
    rename_map = {
        "best_fitness": f"{prefix}_best",
        "avg_fitness": f"{prefix}_avg",
    }
    return df.rename(columns=rename_map)


# ============================================================
# Data File Generation
# ============================================================

def generate_combined_dat(cfg: PlotConfig) -> None:
    """Merge fixed and adaptive logs, write combined .dat file."""
    print(f"Reading {cfg.log_fixed_csv}...")
    df_fixed = load_and_prepare_log(
        cfg.log_fixed_csv,
        cfg.gen_col,
        [cfg.best_col, cfg.avg_col],
        prefix="fixed",
    )

    print(f"Reading {cfg.log_adaptive_csv}...")
    df_adaptive = load_and_prepare_log(
        cfg.log_adaptive_csv,
        cfg.gen_col,
        [cfg.best_col, cfg.avg_col],
        prefix="adapt",
    )

    # Merge on generation column
    df = pd.merge(df_fixed, df_adaptive, on=cfg.gen_col, how="inner")
    df = df.sort_values(cfg.gen_col)

    # Write .dat file
    print(f"Writing {cfg.out_dat}...")
    with open(cfg.out_dat, "w") as f:
        f.write("# gen fixed_best fixed_avg adapt_best adapt_avg\n")
        for _, row in df.iterrows():
            if pd.isna(row[cfg.gen_col]):
                continue
            gen = int(row[cfg.gen_col])
            f.write(
                f"{gen} "
                f"{row['fixed_best']:.10f} {row['fixed_avg']:.10f} "
                f"{row['adapt_best']:.10f} {row['adapt_avg']:.10f}\n"
            )


# ============================================================
# Gnuplot Script Generation
# ============================================================

def _escape_gnuplot_label(label: str) -> str:
    """Escape underscores for gnuplot labels."""
    return label.replace("_", r"\_")


def generate_gnuplot_script(cfg: PlotConfig) -> None:
    """Generate gnuplot script for EPS and PNG output."""
    print(f"Writing {cfg.out_gp}...")

    # Prepare escaped labels
    labels = {k: _escape_gnuplot_label(v) for k, v in CURVE_LABELS.items()}

    script = f"""\
# Anytime Behavior Plot: Fixed vs Adaptive Scheduling
# Auto-generated by temp.py

# --- EPS Output ---
set terminal postscript eps enhanced color font 'Helvetica,36' size 9,6
set output '{cfg.out_eps}'

set title "Anytime Behavior (Fixed vs Adaptive)"
set xlabel "Generation"
set ylabel "Fitness"
set grid

set lmargin 8
set bmargin 3
set rmargin 2
set tmargin 2

set key bottom right spacing 1.2 opaque box

plot '{cfg.out_dat}' using 1:2 with lines lw {cfg.line_width} dt 1 title '{labels["fixed_best"]}', \\
     ''             using 1:3 with lines lw {cfg.line_width} dt 2 title '{labels["fixed_avg"]}', \\
     ''             using 1:4 with lines lw {cfg.line_width} dt 1 title '{labels["adapt_best"]}', \\
     ''             using 1:5 with lines lw {cfg.line_width} dt 4 title '{labels["adapt_avg"]}'

# --- PNG Output ---
set terminal pngcairo size 1800,1200 enhanced font 'Sans,{cfg.png_font_size}'
set output '{cfg.out_png}'

set lmargin 9
set bmargin 4
set rmargin 3
set tmargin 2

set key font ",{cfg.png_key_font_size}" spacing 1.3

replot
"""
    Path(cfg.out_gp).write_text(script)


# ============================================================
# Gnuplot Execution
# ============================================================

def run_gnuplot(script_path: str) -> bool:
    """Execute gnuplot on the given script. Returns True if successful."""
    gnuplot_cmd = shutil.which("gnuplot")
    if not gnuplot_cmd:
        print("Warning: gnuplot not found on PATH (skipping plotting).")
        return False

    try:
        subprocess.run([gnuplot_cmd, script_path], check=True)
        return True
    except subprocess.CalledProcessError as e:
        print(f"Error running gnuplot: {e}")
        return False


# ============================================================
# Main
# ============================================================

def main(cfg: Optional[PlotConfig] = None) -> None:
    """Generate anytime comparison plots."""
    if cfg is None:
        cfg = PlotConfig()

    generate_combined_dat(cfg)
    generate_gnuplot_script(cfg)
    run_gnuplot(cfg.out_gp)

    print("Done.")


if __name__ == "__main__":
    main()
